/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tools;

import DBTools.CalendarDao;
import DBTools.OrderDao;
import DBTools.OrderTemplateDao;
import Models.Order;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

/**
 *
 * @author boxm1
 */
@Service
public class Scheduler {

    @Autowired
    private CalendarDao calendarDao;

    @Autowired
    private OrderDao orderDao;

    @Autowired
    private OrderTemplateDao orderTemplateDao;

//aman ro imushavos dispetcher servletshi unda chacero yvelaperi rac "task" tan aris dakavshirebuli
    @Scheduled(cron = "0 0 20 ? * MON,TUE,WED,THU,FRI,SUN")
    public void executePeriodically() {
        // System.out.println("The time is now : " + new Date());
        calendarDao.lockTheDay();
    }

    @Scheduled(cron = "0 0 5 ? * MON,TUE,WED,THU,FRI,SAT")
    public void executePeriodically2() {
       
        completeOrders();
        generateOrders();

    }

    public void completeOrders() {
        orderDao.completeOrders();
    }

    public void generateOrders() {

        ZoneId athensZone = ZoneId.of("Europe/Athens");
        LocalDate date = LocalDate.now(athensZone);

        DayOfWeek SATURDAY = DayOfWeek.valueOf("SATURDAY");

        if (date.getDayOfWeek()
                == SATURDAY) {
            date = date.plusDays(2);
        } else {
            date = date.plusDays(1);
        }
        int dayOfWeek = date.getDayOfWeek().getValue();

        String day = "day_" + dayOfWeek;

        Map<Integer, Order> ordersMap = orderTemplateDao.getAutogeneratedOrdersListForDay(day);

        for (Order order
                : ordersMap.values()) {
            if (orderDao.checkOrder(order)) {
                //do nothing
            } else {
                orderDao.insertOrder(order);
            }
        }
    }

}
